### ISSUE TITLE
Can't decompress gz files

### ISSUE THREAD

**Issue by rhoef** [DFKI-NLP/smartdata-corpus#1]
The gz files of version3 of the corpus seem  to be broken. Actually, they are ASCII files that do not contain the data. 
Here the output using the ```file``` and ```cat``` command:

```bash
file dev.json.gz 
dev.json.gz: ASCII text
```

```bash
cat dev.json.gz 
version https://git-lfs.github.com/spec/v1
oid sha256:eda57e2d6c3c5517587043052f704ef85c4c10f7bdc28a2e7af3ba074b7d7266
size 1450657
```
thx

**Comment by leonhardhennig** [comment]
Hi,
that is because these files are git-lfs pointers. You need to clone the repository, instead of directly downloading the .gz files. However, cloning currently does not work since we are over our git-lfs quote for this month. To solve this issue, Github recommends deleting and then re-creating the repository with git-lfs, which I will do now. The files should then be directly accessible.

Best, Leo
